[package]
name = "whitelist-ips"
version = "1.3.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libp2p.workspace = true
tracing.workspace = true
tokio.workspace = true
